# logging:
#   level:
#     ROOT: INFO
#     org.springframework: ERROR
#     org.hibernate: ERROR
#     com.kgisl.bootbrite: ALL
  
#   pattern:
#     console: "- %msg%n"
#     file: "*[%-5p]-- %m--%n"
#   file: logs/springbdd.log
# server:
#   port: 8080
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/bootnew
#     username: root
#     password: 
#     driverClassName: com.mysql.cj.jdbc.Driver

  
#   jpa:
#     hibernate:
#       ddl-auto: update
#       show-sql: true
#       database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
